### ISSUE TITLE
multiple destinations

### ISSUE THREAD

**Issue by malak-oz** [Shadi-A/ExpediaCrawler#1]
Hey...

I have no idea how to code, but I've been looking for something like this app for a while...

You might not know, but if you search for multiple destinations, and start or end your trip in a random place, you can end up with much cheaper flights.

Eg. 
HKG-PRG-HKG Dec 21-Jan 2 on British airways... HKD5,600
KUL-HKG in October, then HKG-PRG-HKG Dec 21 - Jan 2... HKD 4,563

Also, Kayak runs searches if you just input the correct URL, without needing to fill in a form on the actual page to run the search.... 

I'm trying to work out how to automatically run a bunch of searches, with randomised one way flights either before or after the "main trip", then dump the results into an Excel document for easy comparison.  

What I'm doing at the moment is running a script in VBA which opens a heap of internet explorer windows with a different search in each window.  Its a pain in the butt to sort it all out.

Any advice you can give would help a lot!

Ps. Sorry for doing this as an 'issue'...i couldn't find your email address.

**Comment by Shadi** [comment]
I like the idea about writing the results to an excel document, I think I'll start with that(once I have time)

I'm not sure how your suggestion would work, in your example you want to travel HKG-PRG, instead you book KUL-HKG and then HKG-PRG-HKG in the same booking? can you send me an example url of a page with that search?

**Comment by malak-oz** [comment]
Thanks for getting back to me...

Here's some URLs with different searches...

https://www.kayak.com.hk/flights/Sin-HKG/2017-09-29/HKG-PRG/2017-12-21/PRG-HKG/2018-01-02/2adults/children-11

https://www.kayak.com.hk/flights/kul-HKG/2017-09-29/HKG-PRG/2017-12-21/PRG-HKG/2018-01-02/2adults/children-11

https://www.kayak.com.hk/flights/Bkk-HKG/2017-09-29/HKG-PRG/2017-12-21/PRG-HKG/2018-01-02/2adults/children-11


On 21 Mar 2017, at 04:09, Shadi-A <notifications@github.com<mailto:notifications@github.com>> wrote:


I like the idea about writing the results to an excel document, I think I'll start with that(once I have time)

I'm not sure how your suggestion would work, in your example you want to travel HKG-PRG, instead you book KUL-HKG and then HKG-PRG-HKG in the same booking? can you send me an example url of a page with that search?

**Comment by Shadi** [comment]
I made a change to the script, there is an optional parameter --file that you can use to append the output to a csv file, see the updated readme file for how to use it.
